//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.02 at 11:48:25 AM EEST 
//


package bg.government.bulstatstats.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * \u0417\u0430\u043f\u0438\u0441
 * 
 * <p>Java class for Entry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Entry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EntryTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Entry", namespace = "http://www.bulstat.bg/Entry", propOrder = {
    "entryTime"
})
@XmlSeeAlso({
    Address.class,
    Attachment.class,
    File.class,
    Case.class,
    Communication.class,
    Document.class,
    Subject.class,
    LegalEntity.class,
    NaturalPerson.class,
    IdentificationDoc.class,
    Event.class,
    UIC.class,
    SubjectPropLifeTime.class,
    SubjectPropState.class,
    SubjectPropScopeOfActivity.class,
    SubjectPropActivityKID2008 .class,
    SubjectPropActivityKID2003 .class,
    SubjectPropInstallments.class,
    SubjectPropRepresentationType.class,
    SubjectPropFundingSource.class,
    SubjectPropOwnershipForm.class,
    SubjectPropAccountingRecordForm.class,
    SubjectPropActivityDate.class,
    SubjectPropProfession.class,
    SubjectPropCollectiveBody.class,
    SubscriptionElement.class
})
public class Entry {

    @XmlElement(name = "EntryTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar entryTime;

    /**
     * Gets the value of the entryTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEntryTime() {
        return entryTime;
    }

    /**
     * Sets the value of the entryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEntryTime(XMLGregorianCalendar value) {
        this.entryTime = value;
    }

}
