//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.02 at 11:48:25 AM EEST 
//


package bg.government.bulstatstats.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetStateOfPlayResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetStateOfPlayResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bulstat.bg/StateOfPlay}StateOfPlay" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetStateOfPlayResponse", namespace = "http://www.bulstat.bg/StateOfPlayService", propOrder = {
    "stateOfPlay"
})
public class GetStateOfPlayResponse {

    @XmlElement(name = "StateOfPlay", namespace = "http://www.bulstat.bg/StateOfPlay")
    protected StateOfPlay stateOfPlay;

    /**
     * Gets the value of the stateOfPlay property.
     * 
     * @return
     *     possible object is
     *     {@link StateOfPlay }
     *     
     */
    public StateOfPlay getStateOfPlay() {
        return stateOfPlay;
    }

    /**
     * Sets the value of the stateOfPlay property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateOfPlay }
     *     
     */
    public void setStateOfPlay(StateOfPlay value) {
        this.stateOfPlay = value;
    }

}
