//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.02 at 11:48:25 AM EEST 
//


package bg.government.bulstatstats.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetStateOfPlay complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetStateOfPlay">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bulstat.bg/GetStateOfPlayRequest}GetStateOfPlayRequest" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetStateOfPlay", namespace = "http://www.bulstat.bg/StateOfPlayService", propOrder = {
    "getStateOfPlayRequest"
})
public class GetStateOfPlay {

    @XmlElement(name = "GetStateOfPlayRequest", namespace = "http://www.bulstat.bg/GetStateOfPlayRequest")
    protected GetStateOfPlayRequest getStateOfPlayRequest;

    /**
     * Gets the value of the getStateOfPlayRequest property.
     * 
     * @return
     *     possible object is
     *     {@link GetStateOfPlayRequest }
     *     
     */
    public GetStateOfPlayRequest getGetStateOfPlayRequest() {
        return getStateOfPlayRequest;
    }

    /**
     * Sets the value of the getStateOfPlayRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetStateOfPlayRequest }
     *     
     */
    public void setGetStateOfPlayRequest(GetStateOfPlayRequest value) {
        this.getStateOfPlayRequest = value;
    }

}
