//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.02 at 11:48:25 AM EEST 
//


package bg.government.bulstatstats.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * \u041d\u043e\u043c\u0435\u043d\u043a\u043b\u0430\u0442\u0443\u0440\u043d\u0430 \u0441\u0442\u043e\u0439\u043d\u043e\u0441\u0442
 * 			
 * 
 * <p>Java class for MultilangNomElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MultilangNomElement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bulstat.bg/NomenclatureEntry}NomenclatureEntry">
 *       &lt;sequence>
 *         &lt;element name="NameBG">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="180"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NameEN">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="180"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Ordering">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="-2147483648"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Active" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultilangNomElement", propOrder = {
    "nameBG",
    "nameEN",
    "ordering",
    "active"
})
@XmlSeeAlso({
    CountryMultilangNomElement.class
})
public class MultilangNomElement
    extends NomenclatureEntry
{

    @XmlElement(name = "NameBG", required = true)
    protected String nameBG;
    @XmlElement(name = "NameEN", required = true)
    protected String nameEN;
    @XmlElement(name = "Ordering", defaultValue = "0")
    protected int ordering;
    @XmlElement(name = "Active")
    protected boolean active;

    /**
     * Gets the value of the nameBG property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameBG() {
        return nameBG;
    }

    /**
     * Sets the value of the nameBG property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameBG(String value) {
        this.nameBG = value;
    }

    /**
     * Gets the value of the nameEN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameEN() {
        return nameEN;
    }

    /**
     * Sets the value of the nameEN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameEN(String value) {
        this.nameEN = value;
    }

    /**
     * Gets the value of the ordering property.
     * 
     */
    public int getOrdering() {
        return ordering;
    }

    /**
     * Sets the value of the ordering property.
     * 
     */
    public void setOrdering(int value) {
        this.ordering = value;
    }

    /**
     * Gets the value of the active property.
     * 
     */
    public boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     */
    public void setActive(boolean value) {
        this.active = value;
    }

}
