//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.02 at 11:48:25 AM EEST 
//


package bg.government.bulstatstats.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * \u0424\u0438\u0437\u0438\u0447\u0435\u0441\u043a\u043e \u043b\u0438\u0446\u0435
 * 
 * <p>Java class for NaturalPerson complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NaturalPerson">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bulstat.bg/Entry}Entry">
 *       &lt;sequence>
 *         &lt;element name="Country" type="{http://www.bulstat.bg/NomenclatureEntry}NomenclatureEntry" minOccurs="0"/>
 *         &lt;element name="EGN" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LNC" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CyrillicName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LatinName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BirthDate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *               &lt;pattern value="\p{Nd}{4}-\p{Nd}{2}-\p{Nd}{2}"/>
 *               &lt;minInclusive value="0001-01-01"/>
 *               &lt;maxInclusive value="9999-12-31"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IdentificationDoc" type="{http://www.bulstat.bg/IdentificationDoc}IdentificationDoc" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NaturalPerson", namespace = "http://www.bulstat.bg/NaturalPerson", propOrder = {
    "country",
    "egn",
    "lnc",
    "cyrillicName",
    "latinName",
    "birthDate",
    "identificationDoc"
})
public class NaturalPerson
    extends Entry
{

    @XmlElement(name = "Country")
    protected NomenclatureEntry country;
    @XmlElement(name = "EGN")
    protected String egn;
    @XmlElement(name = "LNC")
    protected String lnc;
    @XmlElement(name = "CyrillicName", required = true)
    protected String cyrillicName;
    @XmlElement(name = "LatinName", required = true)
    protected String latinName;
    @XmlElement(name = "BirthDate")
    protected XMLGregorianCalendar birthDate;
    @XmlElement(name = "IdentificationDoc")
    protected IdentificationDoc identificationDoc;

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link NomenclatureEntry }
     *     
     */
    public NomenclatureEntry getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link NomenclatureEntry }
     *     
     */
    public void setCountry(NomenclatureEntry value) {
        this.country = value;
    }

    /**
     * Gets the value of the egn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEGN() {
        return egn;
    }

    /**
     * Sets the value of the egn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEGN(String value) {
        this.egn = value;
    }

    /**
     * Gets the value of the lnc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLNC() {
        return lnc;
    }

    /**
     * Sets the value of the lnc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLNC(String value) {
        this.lnc = value;
    }

    /**
     * Gets the value of the cyrillicName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCyrillicName() {
        return cyrillicName;
    }

    /**
     * Sets the value of the cyrillicName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCyrillicName(String value) {
        this.cyrillicName = value;
    }

    /**
     * Gets the value of the latinName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatinName() {
        return latinName;
    }

    /**
     * Sets the value of the latinName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatinName(String value) {
        this.latinName = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the identificationDoc property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificationDoc }
     *     
     */
    public IdentificationDoc getIdentificationDoc() {
        return identificationDoc;
    }

    /**
     * Sets the value of the identificationDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificationDoc }
     *     
     */
    public void setIdentificationDoc(IdentificationDoc value) {
        this.identificationDoc = value;
    }

}
