//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.02 at 11:48:25 AM EEST 
//


package bg.government.bulstatstats.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bg.government.bulstatstats.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SendSubscriptionResponse_QNAME = new QName("http://www.bulstat.bg/SubscriptionService", "SendSubscriptionResponse");
    private final static QName _GetStateOfPlayResponse_QNAME = new QName("http://www.bulstat.bg/StateOfPlayService", "GetStateOfPlayResponse");
    private final static QName _GetStateOfPlayRequest_QNAME = new QName("http://www.bulstat.bg/GetStateOfPlayRequest", "GetStateOfPlayRequest");
    private final static QName _StateOfPlay_QNAME = new QName("http://www.bulstat.bg/StateOfPlay", "StateOfPlay");
    private final static QName _SubscriptionException_QNAME = new QName("http://www.bulstat.bg/SubscriptionService", "SubscriptionException");
    private final static QName _WSException_QNAME = new QName("http://www.bulstat.bg/WSException", "WSException");
    private final static QName _SendSubscriptionRequest_QNAME = new QName("http://www.bulstat.bg/SendSubscriptionRequest", "SendSubscriptionRequest");
    private final static QName _FetchNomenclaturesResponse_QNAME = new QName("http://www.bulstat.bg/StateOfPlayService", "FetchNomenclaturesResponse");
    private final static QName _SendSubscription_QNAME = new QName("http://www.bulstat.bg/SubscriptionService", "SendSubscription");
    private final static QName _FetchNomenclatures_QNAME = new QName("http://www.bulstat.bg/StateOfPlayService", "FetchNomenclatures");
    private final static QName _WSResponse_QNAME = new QName("http://www.bulstat.bg/WSResponse", "WSResponse");
    private final static QName _GetStateOfPlay_QNAME = new QName("http://www.bulstat.bg/StateOfPlayService", "GetStateOfPlay");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bg.government.bulstatstats.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetStateOfPlayRequest }
     * 
     */
    public GetStateOfPlayRequest createGetStateOfPlayRequest() {
        return new GetStateOfPlayRequest();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link NomenclatureEntry }
     * 
     */
    public NomenclatureEntry createNomenclatureEntry() {
        return new NomenclatureEntry();
    }

    /**
     * Create an instance of {@link Attachment }
     * 
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

    /**
     * Create an instance of {@link Employee }
     * 
     */
    public Employee createEmployee() {
        return new Employee();
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link bg.government.bulstatstats.model.Case }
     * 
     */
    public bg.government.bulstatstats.model.Case createCase() {
        return new bg.government.bulstatstats.model.Case();
    }

    /**
     * Create an instance of {@link Communication }
     * 
     */
    public Communication createCommunication() {
        return new Communication();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link Subject }
     * 
     */
    public Subject createSubject() {
        return new Subject();
    }

    /**
     * Create an instance of {@link LegalEntity }
     * 
     */
    public LegalEntity createLegalEntity() {
        return new LegalEntity();
    }

    /**
     * Create an instance of {@link NaturalPerson }
     * 
     */
    public NaturalPerson createNaturalPerson() {
        return new NaturalPerson();
    }

    /**
     * Create an instance of {@link IdentificationDoc }
     * 
     */
    public IdentificationDoc createIdentificationDoc() {
        return new IdentificationDoc();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link UIC }
     * 
     */
    public UIC createUIC() {
        return new UIC();
    }

    /**
     * Create an instance of {@link ExportedData }
     * 
     */
    public ExportedData createExportedData() {
        return new ExportedData();
    }

    /**
     * Create an instance of {@link StateOfPlay }
     * 
     */
    public StateOfPlay createStateOfPlay() {
        return new StateOfPlay();
    }

    /**
     * Create an instance of {@link SubjectPropLifeTime }
     * 
     */
    public SubjectPropLifeTime createSubjectPropLifeTime() {
        return new SubjectPropLifeTime();
    }

    /**
     * Create an instance of {@link SubjectPropState }
     * 
     */
    public SubjectPropState createSubjectPropState() {
        return new SubjectPropState();
    }

    /**
     * Create an instance of {@link SubjectPropScopeOfActivity }
     * 
     */
    public SubjectPropScopeOfActivity createSubjectPropScopeOfActivity() {
        return new SubjectPropScopeOfActivity();
    }

    /**
     * Create an instance of {@link SubjectPropActivityKID2008 }
     * 
     */
    public SubjectPropActivityKID2008 createSubjectPropActivityKID2008() {
        return new SubjectPropActivityKID2008();
    }

    /**
     * Create an instance of {@link SubjectPropActivityKID2003 }
     * 
     */
    public SubjectPropActivityKID2003 createSubjectPropActivityKID2003() {
        return new SubjectPropActivityKID2003();
    }

    /**
     * Create an instance of {@link SubjectPropInstallments }
     * 
     */
    public SubjectPropInstallments createSubjectPropInstallments() {
        return new SubjectPropInstallments();
    }

    /**
     * Create an instance of {@link SubjectPropRepresentationType }
     * 
     */
    public SubjectPropRepresentationType createSubjectPropRepresentationType() {
        return new SubjectPropRepresentationType();
    }

    /**
     * Create an instance of {@link SubjectPropFundingSource }
     * 
     */
    public SubjectPropFundingSource createSubjectPropFundingSource() {
        return new SubjectPropFundingSource();
    }

    /**
     * Create an instance of {@link SubjectPropOwnershipForm }
     * 
     */
    public SubjectPropOwnershipForm createSubjectPropOwnershipForm() {
        return new SubjectPropOwnershipForm();
    }

    /**
     * Create an instance of {@link SubjectPropAccountingRecordForm }
     * 
     */
    public SubjectPropAccountingRecordForm createSubjectPropAccountingRecordForm() {
        return new SubjectPropAccountingRecordForm();
    }

    /**
     * Create an instance of {@link SubjectPropActivityDate }
     * 
     */
    public SubjectPropActivityDate createSubjectPropActivityDate() {
        return new SubjectPropActivityDate();
    }

    /**
     * Create an instance of {@link SubjectPropProfession }
     * 
     */
    public SubjectPropProfession createSubjectPropProfession() {
        return new SubjectPropProfession();
    }

    /**
     * Create an instance of {@link SubjectRelPartner }
     * 
     */
    public SubjectRelPartner createSubjectRelPartner() {
        return new SubjectRelPartner();
    }

    /**
     * Create an instance of {@link SubscriptionElement }
     * 
     */
    public SubscriptionElement createSubscriptionElement() {
        return new SubscriptionElement();
    }

    /**
     * Create an instance of {@link SubjectRelManager }
     * 
     */
    public SubjectRelManager createSubjectRelManager() {
        return new SubjectRelManager();
    }

    /**
     * Create an instance of {@link SubjectRelBelonging }
     * 
     */
    public SubjectRelBelonging createSubjectRelBelonging() {
        return new SubjectRelBelonging();
    }

    /**
     * Create an instance of {@link SubjectRelAssignee }
     * 
     */
    public SubjectRelAssignee createSubjectRelAssignee() {
        return new SubjectRelAssignee();
    }

    /**
     * Create an instance of {@link SubjectPropCollectiveBody }
     * 
     */
    public SubjectPropCollectiveBody createSubjectPropCollectiveBody() {
        return new SubjectPropCollectiveBody();
    }

    /**
     * Create an instance of {@link SubjectRelCollectiveBodyMember }
     * 
     */
    public SubjectRelCollectiveBodyMember createSubjectRelCollectiveBodyMember() {
        return new SubjectRelCollectiveBodyMember();
    }

    /**
     * Create an instance of {@link CountryMultilangNomElement }
     * 
     */
    public CountryMultilangNomElement createCountryMultilangNomElement() {
        return new CountryMultilangNomElement();
    }

    /**
     * Create an instance of {@link MultilangNomElement }
     * 
     */
    public MultilangNomElement createMultilangNomElement() {
        return new MultilangNomElement();
    }

    /**
     * Create an instance of {@link FetchNomenclaturesResponse }
     * 
     */
    public FetchNomenclaturesResponse createFetchNomenclaturesResponse() {
        return new FetchNomenclaturesResponse();
    }

    /**
     * Create an instance of {@link SimpleNomenclature }
     * 
     */
    public SimpleNomenclature createSimpleNomenclature() {
        return new SimpleNomenclature();
    }

    /**
     * Create an instance of {@link MetaDefinition }
     * 
     */
    public MetaDefinition createMetaDefinition() {
        return new MetaDefinition();
    }

    /**
     * Create an instance of {@link SendSubscriptionRequest }
     * 
     */
    public SendSubscriptionRequest createSendSubscriptionRequest() {
        return new SendSubscriptionRequest();
    }

    /**
     * Create an instance of {@link SubjectUIC }
     * 
     */
    public SubjectUIC createSubjectUIC() {
        return new SubjectUIC();
    }

    /**
     * Create an instance of {@link GetStateOfPlayResponse }
     * 
     */
    public GetStateOfPlayResponse createGetStateOfPlayResponse() {
        return new GetStateOfPlayResponse();
    }

    /**
     * Create an instance of {@link FetchNomenclatures }
     * 
     */
    public FetchNomenclatures createFetchNomenclatures() {
        return new FetchNomenclatures();
    }

    /**
     * Create an instance of {@link GetStateOfPlay }
     * 
     */
    public GetStateOfPlay createGetStateOfPlay() {
        return new GetStateOfPlay();
    }

    /**
     * Create an instance of {@link SubscriptionException }
     * 
     */
    public SubscriptionException createSubscriptionException() {
        return new SubscriptionException();
    }

    /**
     * Create an instance of {@link SendSubscriptionResponse }
     * 
     */
    public SendSubscriptionResponse createSendSubscriptionResponse() {
        return new SendSubscriptionResponse();
    }

    /**
     * Create an instance of {@link SendSubscription }
     * 
     */
    public SendSubscription createSendSubscription() {
        return new SendSubscription();
    }

    /**
     * Create an instance of {@link WSResponse }
     * 
     */
    public WSResponse createWSResponse() {
        return new WSResponse();
    }

    /**
     * Create an instance of {@link WSException }
     * 
     */
    public WSException createWSException() {
        return new WSException();
    }

    /**
     * Create an instance of {@link GetStateOfPlayRequest.Case }
     * 
     */
    public GetStateOfPlayRequest.Case createGetStateOfPlayRequestCase() {
        return new GetStateOfPlayRequest.Case();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendSubscriptionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bulstat.bg/SubscriptionService", name = "SendSubscriptionResponse")
    public JAXBElement<SendSubscriptionResponse> createSendSubscriptionResponse(SendSubscriptionResponse value) {
        return new JAXBElement<SendSubscriptionResponse>(_SendSubscriptionResponse_QNAME, SendSubscriptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStateOfPlayResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bulstat.bg/StateOfPlayService", name = "GetStateOfPlayResponse")
    public JAXBElement<GetStateOfPlayResponse> createGetStateOfPlayResponse(GetStateOfPlayResponse value) {
        return new JAXBElement<GetStateOfPlayResponse>(_GetStateOfPlayResponse_QNAME, GetStateOfPlayResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStateOfPlayRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bulstat.bg/GetStateOfPlayRequest", name = "GetStateOfPlayRequest")
    public JAXBElement<GetStateOfPlayRequest> createGetStateOfPlayRequest(GetStateOfPlayRequest value) {
        return new JAXBElement<GetStateOfPlayRequest>(_GetStateOfPlayRequest_QNAME, GetStateOfPlayRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StateOfPlay }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bulstat.bg/StateOfPlay", name = "StateOfPlay")
    public JAXBElement<StateOfPlay> createStateOfPlay(StateOfPlay value) {
        return new JAXBElement<StateOfPlay>(_StateOfPlay_QNAME, StateOfPlay.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubscriptionException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bulstat.bg/SubscriptionService", name = "SubscriptionException")
    public JAXBElement<SubscriptionException> createSubscriptionException(SubscriptionException value) {
        return new JAXBElement<SubscriptionException>(_SubscriptionException_QNAME, SubscriptionException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WSException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bulstat.bg/WSException", name = "WSException")
    public JAXBElement<WSException> createWSException(WSException value) {
        return new JAXBElement<WSException>(_WSException_QNAME, WSException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendSubscriptionRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bulstat.bg/SendSubscriptionRequest", name = "SendSubscriptionRequest")
    public JAXBElement<SendSubscriptionRequest> createSendSubscriptionRequest(SendSubscriptionRequest value) {
        return new JAXBElement<SendSubscriptionRequest>(_SendSubscriptionRequest_QNAME, SendSubscriptionRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FetchNomenclaturesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bulstat.bg/StateOfPlayService", name = "FetchNomenclaturesResponse")
    public JAXBElement<FetchNomenclaturesResponse> createFetchNomenclaturesResponse(FetchNomenclaturesResponse value) {
        return new JAXBElement<FetchNomenclaturesResponse>(_FetchNomenclaturesResponse_QNAME, FetchNomenclaturesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendSubscription }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bulstat.bg/SubscriptionService", name = "SendSubscription")
    public JAXBElement<SendSubscription> createSendSubscription(SendSubscription value) {
        return new JAXBElement<SendSubscription>(_SendSubscription_QNAME, SendSubscription.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FetchNomenclatures }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bulstat.bg/StateOfPlayService", name = "FetchNomenclatures")
    public JAXBElement<FetchNomenclatures> createFetchNomenclatures(FetchNomenclatures value) {
        return new JAXBElement<FetchNomenclatures>(_FetchNomenclatures_QNAME, FetchNomenclatures.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WSResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bulstat.bg/WSResponse", name = "WSResponse")
    public JAXBElement<WSResponse> createWSResponse(WSResponse value) {
        return new JAXBElement<WSResponse>(_WSResponse_QNAME, WSResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStateOfPlay }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bulstat.bg/StateOfPlayService", name = "GetStateOfPlay")
    public JAXBElement<GetStateOfPlay> createGetStateOfPlay(GetStateOfPlay value) {
        return new JAXBElement<GetStateOfPlay>(_GetStateOfPlay_QNAME, GetStateOfPlay.class, null, value);
    }

}
