//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.02 at 11:48:25 AM EEST 
//


package bg.government.bulstatstats.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * \u041b\u0438\u043d\u0435\u0439\u043d\u0430 \u043d\u043e\u043c\u0435\u043d\u043a\u043b\u0430\u0442\u0443\u0440\u0430
 * 			
 * 
 * <p>Java class for SimpleNomenclature complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimpleNomenclature">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Definition" type="{http://www.bulstat.bg/MetaDefinition}MetaDefinition"/>
 *         &lt;element name="NomElement" type="{http://www.bulstat.bg/FetchNomenclaturesResponse}MultilangNomElement" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleNomenclature", propOrder = {
    "definition",
    "nomElement"
})
public class SimpleNomenclature {

    @XmlElement(name = "Definition", required = true)
    protected MetaDefinition definition;
    @XmlElement(name = "NomElement")
    protected List<MultilangNomElement> nomElement;

    /**
     * Gets the value of the definition property.
     * 
     * @return
     *     possible object is
     *     {@link MetaDefinition }
     *     
     */
    public MetaDefinition getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaDefinition }
     *     
     */
    public void setDefinition(MetaDefinition value) {
        this.definition = value;
    }

    /**
     * Gets the value of the nomElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nomElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNomElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MultilangNomElement }
     * 
     * 
     */
    public List<MultilangNomElement> getNomElement() {
        if (nomElement == null) {
            nomElement = new ArrayList<MultilangNomElement>();
        }
        return this.nomElement;
    }

}
