//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.02 at 11:48:25 AM EEST 
//


package bg.government.bulstatstats.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * \u041f\u0440\u0430\u0432\u043e\u043f\u0440\u0438\u0435\u043c\u0441\u0442\u0432\u043e
 * 
 * <p>Java class for SubjectRelAssignee complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubjectRelAssignee">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bulstat.bg/SubscriptionElement}SubscriptionElement">
 *       &lt;sequence>
 *         &lt;element name="RelatedSubjects" type="{http://www.bulstat.bg/Subject}Subject" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Type" type="{http://www.bulstat.bg/NomenclatureEntry}NomenclatureEntry" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubjectRelAssignee", namespace = "http://www.bulstat.bg/SubjectRelAssignee", propOrder = {
    "relatedSubjects",
    "type"
})
public class SubjectRelAssignee
    extends SubscriptionElement
{

    @XmlElement(name = "RelatedSubjects")
    protected List<Subject> relatedSubjects;
    @XmlElement(name = "Type")
    protected NomenclatureEntry type;

    /**
     * Gets the value of the relatedSubjects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedSubjects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedSubjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subject }
     * 
     * 
     */
    public List<Subject> getRelatedSubjects() {
        if (relatedSubjects == null) {
            relatedSubjects = new ArrayList<Subject>();
        }
        return this.relatedSubjects;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link NomenclatureEntry }
     *     
     */
    public NomenclatureEntry getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link NomenclatureEntry }
     *     
     */
    public void setType(NomenclatureEntry value) {
        this.type = value;
    }

}
