//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.02 at 11:48:25 AM EEST 
//


package bg.government.bulstatstats.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * \u0421\u0443\u0431\u0435\u043a\u0442
 * 
 * <p>Java class for Subject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Subject">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bulstat.bg/Entry}Entry">
 *       &lt;sequence>
 *         &lt;element name="UIC" type="{http://www.bulstat.bg/UIC}UIC"/>
 *         &lt;element name="SubjectType" type="{http://www.bulstat.bg/NomenclatureEntry}NomenclatureEntry"/>
 *         &lt;element name="LegalEntitySubject" type="{http://www.bulstat.bg/LegalEntity}LegalEntity" minOccurs="0"/>
 *         &lt;element name="NaturalPersonSubject" type="{http://www.bulstat.bg/NaturalPerson}NaturalPerson" minOccurs="0"/>
 *         &lt;element name="CountrySubject" type="{http://www.bulstat.bg/NomenclatureEntry}NomenclatureEntry" minOccurs="0"/>
 *         &lt;element name="Communications" type="{http://www.bulstat.bg/Communication}Communication" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Addresses" type="{http://www.bulstat.bg/Address}Address" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Remark" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Subject", namespace = "http://www.bulstat.bg/Subject", propOrder = {
    "uic",
    "subjectType",
    "legalEntitySubject",
    "naturalPersonSubject",
    "countrySubject",
    "communications",
    "addresses",
    "remark"
})
public class Subject
    extends Entry
{

    @XmlElement(name = "UIC", required = true)
    protected UIC uic;
    @XmlElement(name = "SubjectType", required = true)
    protected NomenclatureEntry subjectType;
    @XmlElement(name = "LegalEntitySubject")
    protected LegalEntity legalEntitySubject;
    @XmlElement(name = "NaturalPersonSubject")
    protected NaturalPerson naturalPersonSubject;
    @XmlElement(name = "CountrySubject")
    protected NomenclatureEntry countrySubject;
    @XmlElement(name = "Communications")
    protected List<Communication> communications;
    @XmlElement(name = "Addresses")
    protected List<Address> addresses;
    @XmlElement(name = "Remark")
    protected String remark;

    /**
     * Gets the value of the uic property.
     * 
     * @return
     *     possible object is
     *     {@link UIC }
     *     
     */
    public UIC getUIC() {
        return uic;
    }

    /**
     * Sets the value of the uic property.
     * 
     * @param value
     *     allowed object is
     *     {@link UIC }
     *     
     */
    public void setUIC(UIC value) {
        this.uic = value;
    }

    /**
     * Gets the value of the subjectType property.
     * 
     * @return
     *     possible object is
     *     {@link NomenclatureEntry }
     *     
     */
    public NomenclatureEntry getSubjectType() {
        return subjectType;
    }

    /**
     * Sets the value of the subjectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NomenclatureEntry }
     *     
     */
    public void setSubjectType(NomenclatureEntry value) {
        this.subjectType = value;
    }

    /**
     * Gets the value of the legalEntitySubject property.
     * 
     * @return
     *     possible object is
     *     {@link LegalEntity }
     *     
     */
    public LegalEntity getLegalEntitySubject() {
        return legalEntitySubject;
    }

    /**
     * Sets the value of the legalEntitySubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegalEntity }
     *     
     */
    public void setLegalEntitySubject(LegalEntity value) {
        this.legalEntitySubject = value;
    }

    /**
     * Gets the value of the naturalPersonSubject property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalPerson }
     *     
     */
    public NaturalPerson getNaturalPersonSubject() {
        return naturalPersonSubject;
    }

    /**
     * Sets the value of the naturalPersonSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalPerson }
     *     
     */
    public void setNaturalPersonSubject(NaturalPerson value) {
        this.naturalPersonSubject = value;
    }

    /**
     * Gets the value of the countrySubject property.
     * 
     * @return
     *     possible object is
     *     {@link NomenclatureEntry }
     *     
     */
    public NomenclatureEntry getCountrySubject() {
        return countrySubject;
    }

    /**
     * Sets the value of the countrySubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link NomenclatureEntry }
     *     
     */
    public void setCountrySubject(NomenclatureEntry value) {
        this.countrySubject = value;
    }

    /**
     * Gets the value of the communications property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the communications property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommunications().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Communication }
     * 
     * 
     */
    public List<Communication> getCommunications() {
        if (communications == null) {
            communications = new ArrayList<Communication>();
        }
        return this.communications;
    }

    /**
     * Gets the value of the addresses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addresses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddresses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Address }
     * 
     * 
     */
    public List<Address> getAddresses() {
        if (addresses == null) {
            addresses = new ArrayList<Address>();
        }
        return this.addresses;
    }

    /**
     * Gets the value of the remark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemark(String value) {
        this.remark = value;
    }

}
