//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.02 at 11:48:25 AM EEST 
//


package bg.government.bulstatstats.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * \u0423\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b
 * 
 * <p>Java class for SubjectRelManager complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubjectRelManager">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bulstat.bg/SubscriptionElement}SubscriptionElement">
 *       &lt;sequence>
 *         &lt;element name="RelatedSubject" type="{http://www.bulstat.bg/Subject}Subject" minOccurs="0"/>
 *         &lt;element name="Position" type="{http://www.bulstat.bg/NomenclatureEntry}NomenclatureEntry" minOccurs="0"/>
 *         &lt;element name="RepresentedSubjects" type="{http://www.bulstat.bg/Subject}Subject" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubjectRelManager", namespace = "http://www.bulstat.bg/SubjectRelManager", propOrder = {
    "relatedSubject",
    "position",
    "representedSubjects"
})
public class SubjectRelManager
    extends SubscriptionElement
{

    @XmlElement(name = "RelatedSubject")
    protected Subject relatedSubject;
    @XmlElement(name = "Position")
    protected NomenclatureEntry position;
    @XmlElement(name = "RepresentedSubjects")
    protected List<Subject> representedSubjects;

    /**
     * Gets the value of the relatedSubject property.
     * 
     * @return
     *     possible object is
     *     {@link Subject }
     *     
     */
    public Subject getRelatedSubject() {
        return relatedSubject;
    }

    /**
     * Sets the value of the relatedSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subject }
     *     
     */
    public void setRelatedSubject(Subject value) {
        this.relatedSubject = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link NomenclatureEntry }
     *     
     */
    public NomenclatureEntry getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link NomenclatureEntry }
     *     
     */
    public void setPosition(NomenclatureEntry value) {
        this.position = value;
    }

    /**
     * Gets the value of the representedSubjects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the representedSubjects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepresentedSubjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subject }
     * 
     * 
     */
    public List<Subject> getRepresentedSubjects() {
        if (representedSubjects == null) {
            representedSubjects = new ArrayList<Subject>();
        }
        return this.representedSubjects;
    }

}
