//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.02 at 11:48:25 AM EEST 
//


package bg.government.bulstatstats.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * \u0424\u043e\u0440\u043c\u0430 \u043d\u0430 \u0441\u0447\u0435\u0442\u043e\u0432\u043e\u0434\u043d\u043e \u0437\u0430\u043f\u0438\u0441\u0432\u0430\u043d\u0435
 * 
 * <p>Java class for SubjectPropAccountingRecordForm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubjectPropAccountingRecordForm">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bulstat.bg/Entry}Entry">
 *       &lt;sequence>
 *         &lt;element name="Form" type="{http://www.bulstat.bg/NomenclatureEntry}NomenclatureEntry" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubjectPropAccountingRecordForm", namespace = "http://www.bulstat.bg/SubjectPropAccountingRecordForm", propOrder = {
    "form"
})
public class SubjectPropAccountingRecordForm
    extends Entry
{

    @XmlElement(name = "Form")
    protected NomenclatureEntry form;

    /**
     * Gets the value of the form property.
     * 
     * @return
     *     possible object is
     *     {@link NomenclatureEntry }
     *     
     */
    public NomenclatureEntry getForm() {
        return form;
    }

    /**
     * Sets the value of the form property.
     * 
     * @param value
     *     allowed object is
     *     {@link NomenclatureEntry }
     *     
     */
    public void setForm(NomenclatureEntry value) {
        this.form = value;
    }

}
