//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.02 at 11:48:25 AM EEST 
//


package bg.government.bulstatstats.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * \u0415\u043b\u0435\u043c\u0435\u043d\u0442, \u043a\u043e\u0439\u0442\u043e \u043f\u043e\u0434\u043b\u0435\u0436\u0438 \u043d\u0430 \u0432\u043f\u0438\u0441\u0432\u0430\u043d\u0435 \u0438\u043b\u0438 \u0437\u0430\u043b\u0438\u0447\u0430\u0432\u0430\u043d\u0435.
 * 				\u0418\u0437\u043f\u043e\u043b\u0437\u0432\u0430 \u0441\u0435 \u0437\u0430 \u043f\u043e\u0434\u0430\u0432\u0430\u043d\u0435 \u043d\u0430 \u043f\u0440\u043e\u043c\u0435\u043d\u0438 \u043f\u043e \u0430\u0431\u043e\u043d\u0430\u043c\u0435\u043d\u0442.
 * 			
 * 
 * <p>Java class for SubscriptionElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubscriptionElement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bulstat.bg/Entry}Entry">
 *       &lt;sequence>
 *         &lt;element name="OperationType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="register"/>
 *               &lt;enumeration value="erase"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscriptionElement", namespace = "http://www.bulstat.bg/SubscriptionElement", propOrder = {
    "operationType"
})
@XmlSeeAlso({
    SubjectRelPartner.class,
    SubjectRelManager.class,
    SubjectRelBelonging.class,
    SubjectRelAssignee.class,
    SubjectRelCollectiveBodyMember.class
})
public class SubscriptionElement
    extends Entry
{

    @XmlElement(name = "OperationType")
    protected String operationType;

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationType(String value) {
        this.operationType = value;
    }

}
